export enum Role {
  OWNER = 'owner',
  ADMIN = 'admin',
  PRINCIPAL = 'principal',
  VICE_PRINCIPAL = 'vicePrincipal',
  REGISTRAR = 'registrar',
  TEACHER = 'teacher',
  ACCOUNTANT = 'accountant',
  LIBRARIAN = 'librarian',
  RECEPTIONIST = 'receptionist',
  TRANSPORT_MANAGER = 'transportManager',
  HOSTEL_WARDEN = 'hostelWarden',
  NURSE = 'nurse',
  HR = 'hr',
  SECURITY = 'security',
  SUPPORT_STAFF = 'supportStaff',
  MEMBER = 'member',
  GUARDIAN = 'guardian',
}